### ISSUE TITLE
Set up your eclipse to work

### ISSUE THREAD

**Issue by ofiralexi** [TechnionYP5779/team1-bot#1]
Finally ! the time has come we can now work with java :)

Follow the links here:
- https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-maven-eclipse
to download relevant things in order to get you working.
**Make sure** you download the Azure CLI and connect with the bot azure credentials, 
and set your eclipse to java 8 (!) (won't work on other versions of java).
Now that you're all set to start, clone the repo and open it with your eclipse.
-----------------------------------
PROGRAMMING FOR JAVA:
- look at the supplied code, it already gets a business and returns its days, and by day return the opening hours, understand how the code connects with the db and with the dialogflow.
- make sure you wrap every string returned with the utils function, so dialogflow will understand it
-----------------------------------
You can run it locally on your computer ( as described in the tutorial )
Or you can deploy it to azure.
To deploy it:
- run Maven build with package as Goals ( to build your project )
- run Maven build with azure-functions:deploy as Goals ( to deploy it to azure )
Once you deployed you overwrite the existing function, so please make sure you test it first :)
-----------------------------------
- testing:
You can test it with the azure portal, locally on your computer, with fiddler\postman for mocking http requests and even with dialogflow actions on google. Once you have deployed the function is already set on the fullfilment so you should be able to see changes immediately
-----------------------------------
Still have questions? Comment here so others will have the answers and we will try to help you ! :)

+ credit is needed to @Itamaror as well

**Comment by ofiralexi** [comment]
@ShaiZeevi @matanpugach @yoavz1997 @saifun @YarinSh 
Waiting to hear each one succeeded compiling ( and even deploying if needed ) of the code :)

**Comment by ofiralexi** [comment]
> Dont forget that Java 8 is required

@yoavz1997 yep mentioned it in body

**Comment by ShaiZeevi** [comment]
It's not Java 10 compatible?

**Comment by ofiralexi** [comment]
@ShaiZeevi no

**Comment by ofiralexi** [comment]
@ShaiZeevi @yoavz1997 please comment when you've succeeded

**Comment by ShaiZeevi** [comment]
I applied a few tips from the Spartanizer and I'm uploading it to Azure to see I can successfully compile, I believe it worked.
But, is there any way we could fix things up a bit (proper naming for one).
