### ISSUE TITLE
Handle test phrases to homework

### ISSUE THREAD

**Issue by ofiralexi** [TechnionYP5779/team1-bot#10]
Description: Train the Google bot with training phrases so it would catch use input regarding asking for upcoming need to submit homework assigments.

**Comment by ofiralexi** [comment]
![image](https://user-images.githubusercontent.com/37834992/49585876-41c2ca80-f968-11e8-8014-2e580e7dc5ac.png)
I got this error when trying to run, did you add the intent to the switcch in Azure ?

**Comment by Itamaror** [comment]
@ofiralexi  can you please provide the input you used?

**Comment by Itamaror** [comment]
It can also be that the feature is on another branch and a deployment of the azure function from the development branch overwrote my changes. I created a pull request for my branch and once its approved i'll redeploy the homework code.

**Comment by ofiralexi** [comment]
@Itamaror beautiful !!!
![image](https://user-images.githubusercontent.com/37834992/49610980-ca615b00-f9a8-11e8-8b8e-7918873328f6.png)
Just onething, maybe change the answer to be a little more formal ?
![image](https://user-images.githubusercontent.com/37834992/49611003-e107b200-f9a8-11e8-9d7a-f86cc3ec6c3e.png)
Change it and I will be glad to close ! :)

**Comment by Itamaror** [comment]
![image](https://user-images.githubusercontent.com/44427296/49611394-195bc000-f9aa-11e8-9702-c814a401fe67.png)
changed as requested.

**Comment by ofiralexi** [comment]
Approved. closing
