### ISSUE TITLE
Display homeworks as a table of assigments

### ISSUE THREAD

**Issue by ofiralexi** [TechnionYP5779/team1-bot#18]
Display the upcoming homework assigments as a table. ( And not as a simple response )
Added code in the relevant branch that gets list of homework and display them by table.
Connect it with the relevant homework code.

**Comment by ofiralexi** [comment]
@Itamaror can you add a screenshot verifying there is a table of assigments?

**Comment by Itamaror** [comment]
![image](https://user-images.githubusercontent.com/44427296/49701797-a21c6b00-fbf9-11e8-91c3-e63c44bd63d9.png)
@ofiralexi as its shown in actions on google.

**Comment by ofiralexi** [comment]
@Itamaror Approved and merged
