### ISSUE TITLE
Update the wiki to this project

### ISSUE THREAD

**Issue by ofiralexi** [TechnionYP5779/team1-bot#24]
description: Update the bot wiki that will have the relevant pages from team1, and add new pages if needed

**Comment by yoavz1997** [comment]
I've imported some of the wiki pages from the old repo.
In the description, you mentioned that some wiki pages needed to be added, on what subjects?

**Comment by ofiralexi** [comment]
@yoavz1997 I believe it means that the new wiki custom bar should be used, and home page and more if needed for your opinion :)
