### ISSUE TITLE
Meeting after To dos

### ISSUE THREAD

**Issue by ofiralexi** [TechnionYP5779/team1-bot#38]
TO-DOs:
**Administrative:**
- Add issue for opening wiki page on how to run locally

**Parking**
more UI maybe for the parking in the last week

**Bot:**
    **Integrating with calender:**
- Integeate with the phones calender so that you will get follow up alerts on these events:
    - upcoming homework
    - office hours
**Integrating with alerts:**
- Inform the user on invalid academic state - return the avg grades.
- if there had been a test and no grade was given after 10 days, return some alert
**Integrating with Tasks:**
- Try to integrate with Google Keep. I already looked and there is no official API has been published by the Google. unofficial that may be relevant:
    - https://github.com/kiwiz/gkeepapi/
    However, there is a similar mechanism for notes that there is an API for that:
    - https://developers.google.com/tasks/
 
    **Integrating with contacts:**
- information of important people
Try to integrate with contacts so that you will get information for "important" people.
----------------------------------------------- 
Look for customers ideas.
**Potentials customers:**
- the Computer Science Va'ad. 
- ASAT group 
- UG

**Comment by yoavz1997** [comment]
I will look more into Google Tasks API

**Comment by matanpugach** [comment]
I will look into integration with calendar. If you find useful links please share 😸

**Comment by yoavz1997** [comment]
> I will look more into Google Tasks API

I opened a mini [wiki page](https://github.com/TechnionYP5779/team1-bot/wiki/Java-Quickstart-with-Google-Tasks) and I plan on writing a simple API to allow reading and writing tasks to a given user.

**Comment by matanpugach** [comment]
> I will look into integration with calendar. If you find useful links please share 😸

Mine is [here](https://github.com/TechnionYP5779/team1-bot/wiki/Java-quickstart-with-Google-Calendar-API)
