### ISSUE TITLE
Rule system: Store existing rules & activate them

### ISSUE THREAD

**Issue by ShaiZeevi** [TechnionYP5779/team1-bot#42]
We need to formulate a uniform way to add rules, store rules, represent them and activate them.

**Comment by ShaiZeevi** [comment]
Dialogflow api to login, update rules, add rules, activate them.
Also, the DB side of the rules.

**Comment by ShaiZeevi** [comment]
@ofiralexi @matanpugach @saifun @yoavz1997 @Itamaror @YarinSh 

We said the rules would have a structure "if e_1 then perform e_2" where e_1, e_2 are events. What counts as valid events to us? Keep in mind we need to use what we have already implemented (to save work)

**Comment by yoavz1997** [comment]
An event can be the existence of homework, and the result would be creating a task
The same goes for tests.
For instance, when asking the Bot from course information, we can ask the user if she would like to add that test to her calendar.

**Comment by yoavz1997** [comment]
A bundle of multiple issues #49 #50 #51
