### ISSUE TITLE
Parsing course keywords 

### ISSUE THREAD

**Issue by ShaiZeevi** [TechnionYP5779/team1-bot#46]
From the english site

**Comment by matanpugach** [comment]
why am i assigned?

**Comment by ShaiZeevi** [comment]
I was told to assign you, @matanpugach

**Comment by matanpugach** [comment]
what? @ShaiZeevi

**Comment by ShaiZeevi** [comment]
I’ve updated the comment @matanpugach

**Comment by matanpugach** [comment]
@ShaiZeevi the code is in PR and anyone can continue it. When was this issue discussed/ or described ? there was no formal conversation about it.

**Comment by ShaiZeevi** [comment]
It is needed for the “course recommendation” feature #6

**Comment by yoavz1997** [comment]
DONE a45819d1775c2aef8d40209875649f33c9cbab7d
