### ISSUE TITLE
Subscribe

### ISSUE THREAD

**Issue by yoavz1997** [TechnionYP5779/team1-bot#49]
Description: add an option for the user to subscribe to a rule in the rule system

**Comment by ofiralexi** [comment]
@ShaiZeevi finished code-side. Please add the dialogflow side support and tag as NEEDS REVIEW so we can close this :)

**Comment by matanpugach** [comment]
@ofiralexi @ShaiZeevi the code was already merged, can I close?

**Comment by ShaiZeevi** [comment]
I'll close them now
