### ISSUE TITLE
Give information about video existance

### ISSUE THREAD

**Issue by ofiralexi** [TechnionYP5779/team1-bot#5]
Description: given a course name or number, tell if there is a video to the course, and if so where is it. ( Panopto ? Old video service? Maybe we can even check youtube ?)
For this you will need:
- [x] Parse the video servers
- [x] logic of checking video existance
- [x] an Intent matching the test phrases ( and document them )
- [x] connect the intent to the logic using Azure

**Comment by ShaiZeevi** [comment]
![image](https://user-images.githubusercontent.com/36810747/50156687-14ffa300-02d8-11e9-9bf4-974214f9645a.png)

Basic Search complete (the picture depicted is from a local run)

**Comment by matanpugach** [comment]
Please check this was merged or open a PR

**Comment by ShaiZeevi** [comment]
Opened a PR @ofiralexi @Itamaror

**Comment by ofiralexi** [comment]
Reviewed and merged.Closing
