### ISSUE TITLE
Run rules

### ISSUE THREAD

**Issue by yoavz1997** [TechnionYP5779/team1-bot#51]
Description: a descriptive title

**Comment by ShaiZeevi** [comment]
Here is the intent:

![image](https://user-images.githubusercontent.com/36810747/50422781-15f38000-0856-11e9-9ab0-f61b54da2283.png)

It relies on the fact the uname & passwd are stored in the context (o.w. the webhook will send back an exception).

Also, for now it only supports Homework subscription rules.

Finally, I ran it locally with postman and got the proper results (showing only partial results for everyone's sake, it's very long):

![image](https://user-images.githubusercontent.com/36810747/50422864-00cb2100-0857-11e9-82d5-92296658a0d6.png)
