### ISSUE TITLE
Improve UI 

### ISSUE THREAD

**Issue by matanpugach** [TechnionYP5779/team1-bot#57]
different responses and try to color the table

**Comment by Itamaror** [comment]
Added card responses that support pictures to getBusinessHours Intents.

![image](https://user-images.githubusercontent.com/44427296/50458464-ff3f4d00-096b-11e9-8155-3070cbf513e8.png)

**Comment by yoavz1997** [comment]
Wow! It looks amazing!
When you display the text below, can you add '\n' between each day's info?

**Comment by Itamaror** [comment]
The text already contains the '\n's but for some reason they are ignored. I am considering turning it into a table instead.

**Comment by yoavz1997** [comment]
That is also a valid option.
Are there any other response types which match this particular case?

**Comment by Itamaror** [comment]
Changed the filter courses response into a table response (the same one used for post-requisites).
The answer limit was removed temporarily but I am thinking we can remove it because the output is now scrollable. @ShaiZeevi  I'd be happy to hear your thought about it.

![image](https://user-images.githubusercontent.com/44427296/50459050-60691f80-0970-11e9-95f4-62ef69059d42.png)

**Comment by Itamaror** [comment]
> 
> 
> That is also a valid option.
> Are there any other response types which match this particular case?

Well there are only two types of responses implemented as of yet Table and Card. You can see the rest here: https://developers.google.com/actions/assistant/responses
Let me know if there is anything that catches your eye.

**Comment by ofiralexi** [comment]
Beautiful ! maybe turning it into a table will solve the problem, but there is also a carousle if it can be implemented inside.
@Itamaror Were there pictures in the DB ? I wonder if I remembered correctly

**Comment by Itamaror** [comment]
> 
> 
> Beautiful ! maybe turning it into a table will solve the problem, but there is also a carousle if it can be implemented inside.
> @Itamaror Were there pictures in the DB ? I wonder if I remembered correctly

Yes there were pictures for each business.
Great forward thinking by the DB creators.

**Comment by yoavz1997** [comment]
> > That is also a valid option.
> > Are there any other response types which match this particular case?
> 
> Well there are only two types of responses implemented as of now, Table and Card. You can see the rest here: https://developers.google.com/actions/assistant/responses
> Let me know if there is anything that catches your eye.

Funny you say that, but there is a Table Card response which seems fitting, but a simple table is also a great option

**Comment by Itamaror** [comment]
> 
> 
> > > That is also a valid option.
> > > Are there any other response types which match this particular case?
> > 
> > 
> > Well there are only two types of responses implemented as of now, Table and Card. You can see the rest here: https://developers.google.com/actions/assistant/responses
> > Let me know if there is anything that catches your eye.
> 
> Funny you say that, but there is a Table Card response which seems fitting, but a simple table is also a great option

You are right, the table response I talked about is the table card response, there is no simple table response.
The current implementation doesn't support the addition of pictures. I am probably going to end up expanding it to include one.

**Comment by Itamaror** [comment]
Added a picture to the business hours table response.

![image](https://user-images.githubusercontent.com/44427296/50475936-e6b44e80-09ce-11e9-8c7a-2d84fdc4fd67.png)

**Comment by ShaiZeevi** [comment]
@Itamaror I like the new design very much, great job

**Comment by Itamaror** [comment]
And what about the course count limitation? Should we add it back?

**Comment by ShaiZeevi** [comment]
> And what about the course count limitation? Should we add it back?

I see no reason to do so. If the user believes he/she had seen enough, they can just close the card. Correct?

**Comment by Itamaror** [comment]
They can scroll away from it. The screen space it takes isn't really significant.

**Comment by ShaiZeevi** [comment]
> They can scroll away from it. The screen space it takes isn't really significant.

Ok then. I suggest we leave it at that for the time being

**Comment by matanpugach** [comment]
Video UI improvement: 

1. For a course with a single video source (such as lecture only): `does course 234319 have a video?` you now get: (generated a card containing a button)
<img width="246" alt="image" src="https://user-images.githubusercontent.com/27849930/50487294-627dbd80-0a06-11e9-9995-3cb9c25fc358.png">

2. For a course with multiple video source (such as lecture & tutorial): `does course 114073 have a video?` you now get: (required a different card type called Browsing carousel in which the buttons are through the pictures):
![image](https://user-images.githubusercontent.com/27849930/50487495-50504f00-0a07-11e9-8344-965b16ec3b11.png)

If you click a link you are redirected to the page corresponding with the query:
![image](https://user-images.githubusercontent.com/27849930/50487524-652ce280-0a07-11e9-83d5-803ebe070579.png)

**Comment by Itamaror** [comment]
As the PR was approved i am closing this issue #64.
