### ISSUE TITLE
Fix the DB

### ISSUE THREAD

**Issue by matanpugach** [TechnionYP5779/team1-bot#58]
Courses field prerequisites should contain names and not numbers.

**Comment by ShaiZeevi** [comment]
@saifun @yoavz1997 @ofiralexi @matanpugach @YarinSh @Itamaror 

I believe I have an alternative to the situation. Which means no changed need to take place.

Say that we found course A and its prereq's are (B&C | D&E)

To find out B-E's names we can do the following.
I assume you have a list containing the courseNumbers, we'll call it nums.

Then, run the query (SELECT courseNumber, name FROM Courses WHERE courseNumber IN (B,C,D,E)).
You can use nums to do so.

Then, traverse the result set. Each tuple gives you the name of a course you need

Here is an example of the IN operator in action:
![image](https://user-images.githubusercontent.com/36810747/50444104-39c6cc80-090f-11e9-93a4-31fbb5f4fae1.png)

**Comment by matanpugach** [comment]
@ShaiZeevi Sounds good. closing.

**Comment by ShaiZeevi** [comment]
@matanpugach we can't close it on our own accord, the other teammates must weigh in.

@ofiralexi I believe you were against the idea & for the change.

**Comment by Itamaror** [comment]
I think that any idea which involves not changing the database is a welcome idea.
This will probably save us from breaking any existing code.
The idea itself is easy enough to implement.

**Comment by ofiralexi** [comment]
@Itamaror so can you say when trying to implement postrequisites any other thoughts of this solution ?

**Comment by Itamaror** [comment]
> 
> 
> @Itamaror so can you say when trying to implement postrequisites any other thoughts of this solution ?

I am not sure if I understood you correctly ,Technically speaking I can do something similar to implement the postrequisites feature using the LIKE keyword, but I already have a working implementation that uses a separate DB.
I guess if you think this is not efficient enough, we should consider another option.

**Comment by Itamaror** [comment]
Yep I am returning the names, you can see picture in thr relevant issue: #4

**Comment by saifun** [comment]
Acknowledged. 
Thanks all for the help!
