### ISSUE TITLE
Filter courses by categories

### ISSUE THREAD

**Issue by ofiralexi** [TechnionYP5779/team1-bot#7]
Description: support course filtering by name, faculty , exams dates, number of lecture and tutorials hours.

**Comment by ShaiZeevi** [comment]
note to self:
- add date filtering
- check what happens when faculty == none but other parameters exist
- once done adding criteria transfer to list card to allow scrolling

**Comment by ShaiZeevi** [comment]
![image](https://user-images.githubusercontent.com/36810747/49833695-f6af1a00-fda2-11e8-8278-4869ed1f763b.png)
![image](https://user-images.githubusercontent.com/36810747/49833705-00388200-fda3-11e8-91ab-8fc36b043f1d.png)
![image](https://user-images.githubusercontent.com/36810747/49833717-09295380-fda3-11e8-9c82-23ab86c125a0.png)
