### ISSUE TITLE
Manage and Organize Wiki Pages

### ISSUE THREAD

**Issue by saifun** [TechnionYP5779/team1-bot#72]

**Comment by ShaiZeevi** [comment]
What kind of upkeep is required?

**Comment by saifun** [comment]
I moved some missing pages from team1 wiki, and added a sidebar to make things more organized.

**Comment by ShaiZeevi** [comment]
I think some more pages need moving. A few general ones like 'Github issues in eclipse' since we are still using Eclipse.
Also, what do you think about the 'team meeting 3,4,5' pages? Are they relevant here?

**Comment by saifun** [comment]
I hesitated whether to move the 'Github issues in eclipse', so if you also think it's needed I'll move it now.
As for meetings 3,4,5 - I think that 3 and 4 are really not related, but I'll move 5 as well.

**Comment by ShaiZeevi** [comment]
Cool
